version: '3.8'

services:
  front-pep3:
    image: derflinger/pep3devsecops_frontend
    container_name: pep3_frontend
    ports:
      - "3000:80"
    restart: always
    networks:
      - pep3-network

networks:
  pep3-network:
    external: true
