version: "3.8"

services:
  app:
    container_name: pep3devsecops_backend
    image: derflinger/pep3devsecops_backend
    ports:
      - "8097:8097"
    environment:
      # Conexión a Neon Database
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-small-star-a29vm0le-pooler.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_34UwzufKSYHt
      - SPRING_PROFILES_ACTIVE=docker
      - spring.sql.init.mode=never        # evita inicialización automática
      - spring.jpa.hibernate.ddl-auto=none
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8097/emergencies/all"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Ya no necesitamos el contenedor de PostgreSQL ni volúmenes
# volumes:
#   postgres_data: